#!/usr/bin/env node

"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const PROJECT_ROOT = path.resolve(__dirname, "..");
const REPOSITORY_ROOT = path.resolve(PROJECT_ROOT, "..");
let assertions = 0;

function check(condition, message) {
    assertions += 1;
    assert(condition, message);
}

function readProjectFile(relativePath) {
    return fs.readFileSync(path.join(PROJECT_ROOT, relativePath), "utf8");
}

try {
    const plan = readProjectFile("docs/ALB-135_PRODUCT_UI_FINALIZATION.md");
    const marketplacePlan = readProjectFile("docs/ALB-134_ADOBE_MARKETPLACE_READINESS.md");
    const supportPlan = readProjectFile("marketplace/SUPPORT_LEGAL_AND_MEDIA_PLAN.md");
    const roadmap = readProjectFile("docs/ROADMAP.md");
    const readme = readProjectFile("README.md");
    const packageJson = JSON.parse(readProjectFile("package.json"));
    const identity = readProjectFile("src/config/buildIdentity.js");
    const openFolder = readProjectFile("src/components/OpenFolder.jsx");
    const templatePanel = readProjectFile("src/components/TemplateDocumentPanel.jsx");
    const photoBrowser = readProjectFile("src/components/PhotoBrowserSection.jsx");
    const photoBrowserModel = readProjectFile("src/services/PhotoBrowserModel.js");
    const photoGroupingEngine = readProjectFile("src/services/PhotoGroupingEngine.js");
    const jpegRenderer = readProjectFile("src/services/SoftwareJpegRenderer.js");
    const projectService = readProjectFile("src/services/ProjectService.js");
    const thumbnailGrid = readProjectFile("src/components/ThumbnailGrid.jsx");
    const thumbnailCard = readProjectFile("src/components/ThumbnailCard.jsx");
    const panelController = readProjectFile("src/controllers/PanelController.jsx");
    const styles = readProjectFile("src/styles.css");
    const index = fs.readFileSync(
        path.join(REPOSITORY_ROOT, "ALB-116_ENGINEERING_RECORD_INDEX.md"),
        "utf8"
    );

    check(plan.includes("Status: **implementation in progress — responsive runtime qualification started**"), "implementation status differs");
    check(plan.includes("P0 — runtime entry and panel visibility"), "runtime visibility priority is missing");
    check(plan.includes("Developer/diagnostic actions compete"), "Design action-hierarchy finding is missing");
    check(plan.includes("Minimum dock | 320x500"), "minimum-dock acceptance is missing");
    check(plan.includes("Preferred dock | 420x800"), "preferred-dock acceptance is missing");
    check(plan.includes("Preferred floating | 900x700"), "floating acceptance is missing");
    check(plan.includes("Marketplace review | 1360x800"), "Marketplace-size acceptance is missing");
    check(plan.includes("ALB-135.2 — workspace shell"), "next implementation slice is missing");
    check(plan.includes("ALB-135.5 — responsive runtime qualification"), "runtime qualification slice is missing");
    check(plan.includes("Import → Sort → Cull → Enhance → Design → Export"), "approved workflow foundation is missing");
    check(plan.includes("Canonical prototype recovery and priority reset"), "canonical prototype recovery record is missing");
    check(plan.includes("Canonical header and workflow navigation alignment"), "prototype shell-alignment record is missing");
    check(plan.includes("equivalent UXP-safe Flex layout"), "live workflow-tab fallback evidence is missing");
    check(plan.includes("per-camera clock offsets"), "multi-camera clock correction provision is missing");
    check(plan.includes("bride/groom and\n  outfit continuity"), "future visual story evidence is missing");
    check(plan.includes("cover, wrapper, index, story spreads"), "future album-structure provision is missing");
    check(plan.includes("Approved PSD templates remain the deterministic design source"), "template fallback boundary is missing");
    check(plan.includes("capability-gated by ALB-070"), "future AI gate boundary is missing");
    check(plan.includes("ALB-135.2 implementation progress"), "workspace-shell implementation record is missing");
    check(plan.includes("Plugin Reload Successful"), "updated-bundle reload evidence is missing");
    check(plan.includes("Plugin Load Successful"), "clean plugin-load evidence is missing");
    check(plan.includes("900x700\npanel document"), "runtime panel-mount evidence is missing");
    check(plan.includes("Reset Essentials"), "workspace-reset evidence is missing");
    check(plan.includes("expanding that collapsed dock surfaced"), "visible panel evidence is missing");
    check(plan.includes("ALB-135.2 remains open only for inspecting"), "remaining runtime acceptance boundary is missing");
    check(plan.includes("CSS Grid box measured 0x0"), "UXP header-collapse diagnosis is missing");
    check(plan.includes("non-shrinking, wrapping flex layout"), "UXP header runtime fix is missing");
    check(plan.includes("panel document at **420x675**"), "live panel measurement evidence is missing");
    check(plan.includes("live 420-pixel Photoshop dock width"), "preferred-dock runtime evidence is missing");
    check(plan.includes("320x500 visual check remains environment-limited"), "minimum-dock runtime boundary is missing");
    check(plan.includes("900x700 visual check remains open"), "floating runtime boundary is missing");
    check(plan.includes("ALB-135.3 implementation progress"), "Import/Sort/Cull implementation record is missing");
    check(plan.includes("Persistent manual drag ordering"), "remaining Sort-workbench boundary is missing");
    check(plan.includes("six-photo REC005 fixture"), "Import/Sort/Cull runtime evidence is missing");
    check(plan.includes("Persistent manual story order"), "manual story-order implementation record is missing");
    check(plan.includes("path-free ordered list"), "manual order privacy boundary is missing");
    check(plan.includes("Multi-photo story moves and session undo"), "multi-photo order implementation record is missing");
    check(plan.includes("move all 6 together"), "multi-photo order runtime evidence is missing");
    check(photoBrowser.includes("secondaryFiltersOpen"), "secondary filter disclosure state is missing");
    check(photoBrowser.includes('aria-controls="photo-browser-secondary-filters"'), "secondary filter disclosure is not connected to its panel");
    check(photoBrowser.includes("Filters{secondaryFilterCount"), "active secondary filter count is missing");
    check(photoBrowser.includes('{ value: "manual", label: "Manual Order" }'), "manual order sort option is missing");
    check(photoBrowser.includes("onReorderPhoto={handleManualReorder}"), "manual drag reorder is not connected to the photo grid");
    check(photoBrowser.includes("Clear filters before editing the full story order."), "filtered manual-order guard is missing");
    check(photoBrowserModel.includes("normalizePhotoStoryOrder"), "manual story-order normalization is missing");
    check(photoBrowserModel.includes("movePhotosInStoryOrder"), "multi-photo story movement is missing");
    check(photoBrowser.includes("handleStoryOrderTravel"), "manual story-order undo/redo is missing");
    check(photoBrowser.includes("handleStoryOrderReset"), "manual story-order reset is missing");
    check(photoBrowser.includes("move all ${selectedCount} together"), "multi-photo move guidance is missing");
    check(projectService.includes('"photoStoryOrder"'), "project metadata validation omits manual story order");
    check(photoBrowser.includes("Align camera clocks"), "camera clock correction UI is missing");
    check(photoBrowser.includes("cameraClockOffsets"), "camera clock correction persistence is not connected");
    check(photoGroupingEngine.includes("normalizeCameraClockOffsets"), "camera correction normalization is missing");
    check(photoGroupingEngine.includes("applyCameraClockCorrections"), "camera correction projection is missing");
    check(jpegRenderer.includes("cameraMake"), "JPEG camera make extraction is missing");
    check(jpegRenderer.includes("cameraModel"), "JPEG camera model extraction is missing");
    check(projectService.includes('"cameraClockOffsets"'), "project metadata validation omits camera corrections");
    check(photoBrowser.includes("Event chapters"), "manual event chapter UI is missing");
    check(photoBrowser.includes("handleCreateEventChapter"), "manual event creation is not connected");
    check(photoBrowser.includes("handleRenameEventChapter"), "manual event rename is not connected");
    check(photoBrowser.includes("handleMoveEventChapter"), "manual event reorder is not connected");
    check(photoBrowserModel.includes("normalizePhotoEventChapters"), "manual event normalization is missing");
    check(photoBrowserModel.includes("assignPhotosToEventChapter"), "manual event photo assignment is missing");
    check(photoBrowserModel.includes("findUnassignedPhotoEventChapterPhotos"), "unassigned event-photo review is missing");
    check(photoBrowserModel.includes("removePhotosFromEventChapters"), "manual event membership removal is missing");
    check(photoBrowserModel.includes("deleteEmptyPhotoEventChapter"), "safe empty-event deletion is missing");
    check(photoBrowserModel.includes("mergePhotoEventChapters"), "safe event merging is missing");
    check(photoBrowserModel.includes("summarizePhotoEventChapterReview"), "Sort completion summary is missing");
    check(photoBrowser.includes("Select Unassigned"), "unassigned-photo selection action is missing");
    check(photoBrowser.includes("Remove selected"), "manual event membership removal action is missing");
    check(photoBrowser.includes("Delete empty"), "empty-event deletion action is missing");
    check(photoBrowser.includes("Merge ↑"), "merge-with-previous action is missing");
    check(photoBrowser.includes("Sort incomplete"), "incomplete Sort warning is missing");
    check(photoBrowser.includes("Continue to Cull →"), "Sort-to-Cull handoff is missing");
    check(photoBrowser.includes("Cull incomplete"), "incomplete Cull warning is missing");
    check(photoBrowser.includes("Review Unrated"), "unrated-photo review action is missing");
    check(photoBrowser.includes("Continue to Enhance →"), "Cull-to-Enhance handoff is missing");
    check(openFolder.includes('activeWorkspaceMode === "ENHANCE"'), "Enhance review workspace is missing");
    check(openFolder.includes("Continue to Design →"), "Enhance-to-Design handoff is missing");
    check(photoGroupingEngine.includes('key: "ENHANCE"'), "six-step workflow omits Enhance");
    check(photoGroupingEngine.includes('targetStep > 6'), "wizard navigation is not bounded to six steps");
    check(openFolder.includes("groupsReviewed: sortReviewStatus.ready"), "workflow completion ignores Sort review status");
    check(openFolder.includes("unassigned photos before Cull"), "locked Cull guidance omits unassigned photos");
    check(openFolder.includes("cullReviewStatus.ready ? cullReviewStatus.kept : 0"), "workflow completion ignores canonical Cull review status");
    check(openFolder.includes("unrated photos before Enhance"), "locked Enhance guidance omits unrated photos");
    check(openFolder.includes("Reviewed Cull source"), "reviewed Design source summary is missing");
    check(openFolder.includes("Manual Designer entry"), "manual Designer entry warning is missing");
    check(openFolder.includes("Open Designer Manually →"), "manual Designer shortcut is not explicit");
    check(openFolder.includes("getPhotoDecision={designPhotoDecisionLookup}"), "Auto-Flow does not receive canonical photo decisions");
    check(photoBrowser.includes("Continue to Enhance →"), "reviewed Enhance entry action is missing");
    check(openFolder.includes("Create Album Draft"), "primary Design draft action is missing");
    check(openFolder.includes('aria-expanded={manualSpreadToolsOpen}'), "manual spread disclosure is missing");
    check(openFolder.includes("manualSpreadToolsOpen &&"), "manual spread tools are not collapsed by default");
    check(templatePanel.includes('aria-expanded={advancedExecutionOpen}'), "advanced execution disclosure is missing");
    check(templatePanel.includes("advancedExecutionOpen &&"), "advanced execution controls are not collapsed by default");
    check(templatePanel.indexOf("Process Project") < templatePanel.indexOf("Advanced Execution"), "production processing is not presented before advanced execution");
    check(templatePanel.includes('aria-expanded={templateManagementVisible}'), "template management disclosure is missing");
    check(templatePanel.includes("templateManagementRequired || openSettings === 1"), "empty or blocked template management is not forced visible");
    check(templatePanel.includes("Manage Templates"), "compact healthy-registry action is missing");
    check(templatePanel.includes(">#{index + 1} ·</span>"), "template order is not visually separated from its filename");
    check(templatePanel.includes(">· {status}</span>"), "template filename is not visually separated from validation status");
    check(templatePanel.includes('aria-expanded={outputSettingsVisible}'), "output settings disclosure is missing");
    check(templatePanel.includes("outputSettingsRequired || openSettings === 2"), "active output settings are not forced visible");
    check(templatePanel.includes("Auto Save {autoSaveEnabled"), "compact output status is missing");
    check(templatePanel.indexOf("Project Templates") < templatePanel.indexOf("Process Project"), "template summary is not presented before processing");
    check(projectService.includes('"photoEventChapters"'), "project metadata validation omits manual events");
    check(plan.includes("Manual event chapters"), "manual event chapter implementation record is missing");
    check(plan.includes("Reception membership restored"), "manual event runtime persistence evidence is missing");
    check(plan.includes("Unassigned-photo review and chapter membership"), "unassigned-photo workflow record is missing");
    check(plan.includes("one-photo/one-chapter invariant"), "manual chapter membership safety boundary is missing");
    check(plan.includes("Safe chapter lifecycle editing"), "chapter lifecycle implementation record is missing");
    check(plan.includes("retains the preceding\nchapter's identity and name"), "safe merge identity boundary is missing");
    check(plan.includes("Sort completion and Cull handoff"), "Sort completion implementation record is missing");
    check(plan.includes("does not infer completion from photo presence alone"), "Sort completion safety rule is missing");
    check(plan.includes("Cull completion and Design handoff"), "Cull completion implementation record is missing");
    check(plan.includes("every current photo is explicitly"), "Cull completion decision boundary is missing");
    check(plan.includes("Go to Designer** command remains an intentional manual"), "explicit Designer shortcut boundary is missing");
    check(plan.includes("Design entry source clarity"), "Design entry source implementation record is missing");
    check(plan.includes("never falls back from Kept Photos to unrated photos"), "strict Auto-Flow source boundary is missing");
    check(plan.includes("Design primary-action hierarchy"), "Design hierarchy implementation record is missing");
    check(plan.includes("Advanced Execution** disclosure"), "advanced execution boundary is missing");
    check(plan.includes("Compact template and output management"), "compact template/output implementation record is missing");
    check(plan.includes("idle recovery panel already returns no UI"), "idle recovery visibility boundary is missing");
    check(plan.includes("ALB-135.5 responsive runtime qualification"), "responsive runtime qualification record is missing");
    check(plan.includes("approximately 320 pixels"), "minimum-dock runtime evidence is missing");
    check(plan.includes("#1 · filename · Ready"), "template-row runtime clarity evidence is missing");
    check(plan.includes("AlbumAI Pro · project"), "brand/project runtime clarity evidence is missing");
    check(plan.includes("Bring All to Front** did not surface"), "floating-panel limitation evidence is missing");
    check(thumbnailGrid.includes("handleReorderDrop"), "manual reorder drop routing is missing");
    check(thumbnailCard.includes("is-reorder-target"), "manual reorder target feedback is missing");
    check(styles.includes(".photo-filter-panel"), "secondary filter panel styling is missing");
    check(openFolder.includes("workspace-brand-mark"), "compact workspace brand mark is missing");
    check(openFolder.includes('className="workspace-project-group"'), "prototype project identity group is missing");
    check(openFolder.includes('role="tablist" aria-label="Album workflow"'), "prototype workflow tablist is missing");
    check(openFolder.includes("aria-selected={isActive}"), "workflow tab selection state is missing");
    check(!openFolder.includes("wizard-step-icon"), "legacy circular workflow markers remain rendered");
    check(styles.includes(".workspace-project-group {\n        display: none;"), "compact-dock project compaction is missing");
    check(styles.includes("border-bottom-color: #58a6ff"), "prototype active-tab underline is missing");
    check(styles.includes(".wizard-step-bar {\n    display: flex;"), "workflow tabs do not use the UXP-safe flex layout");
    check(photoBrowser.includes('className="photo-workflow-intro"'), "prototype Import/Sort screen heading hierarchy is missing");
    check(photoBrowser.includes('"Import photos"'), "Import screen title is missing");
    check(photoBrowser.includes('"Build the shooting sequence"'), "Sort screen title is missing");
    check(photoBrowser.includes("Continue to Sort →"), "Import-to-Sort primary handoff is missing");
    check(photoBrowser.includes("AI story <em>Future</em>"), "future AI story provision is not visibly bounded");
    check(photoBrowser.includes("photos.length > 0 && workflowStep === 3"), "culling controls are not isolated to the Cull step");
    check(styles.includes(".photo-workflow-intro"), "Import/Sort screen heading styling is missing");
    check(openFolder.includes("Step {activeWizardStep.id} of {WIZARD_STEPS.length}"), "docked active-step context is missing");
    check(openFolder.includes("workspace-quick-btn workspace-quick-btn--primary"), "Save action hierarchy is missing");
    check(!openFolder.includes("<span>✨ AlbumAI Pro</span>"), "legacy emoji product title remains");
    check(!openFolder.includes("wizard-step-connector"), "legacy workflow connectors remain rendered");
    check(styles.includes(".workspace-top-bar {\n    display: flex;"), "UXP-safe workspace-shell flex layout is missing");
    check(styles.includes("flex: 0 0 auto;\n    flex-wrap: nowrap;"), "workspace header can collapse in the UXP flex root");
    check(!styles.includes("grid-template-columns: minmax(170px, auto) minmax(260px, 1fr) auto"), "unsupported workspace-shell grid remains");
    check(styles.includes(".workspace-step-context"), "responsive active-step styling is missing");
    check(styles.includes(".workspace-quick-btn--primary"), "primary header action styling is missing");
    check(panelController.includes("create(rootNode)"), "Manifest v5 panel create signature is missing");
    check(panelController.includes("rootNode.appendChild(this[_root])"), "panel content is not attached during create");
    check(panelController.includes("show(rootNode)"), "Manifest v5 panel show signature is missing");
    check(panelController.includes("ReactDOM.unmountComponentAtNode"), "panel destroy does not release the React root");
    check(plan.includes("No permanent logo decision and no final Marketplace screenshots"), "visual-asset boundary is missing");
    check(marketplacePlan.includes("Final screenshot capture is explicitly\ndeferred"), "ALB-134 screenshot boundary changed");
    check(supportPlan.includes("temporary Option 3 icon remains candidate-test artwork only"), "temporary-icon boundary changed");
    check(packageJson.version === "1.2.1", "UI planning changed the candidate version");
    check(identity.includes("ALB-134-v1.2.1-marketplace-candidate-v1"), "UI planning changed runtime identity");
    check(packageJson.scripts["test:alb135"] === "node tests/run-alb135-tests.js", "ALB-135 script differs");
    check(packageJson.scripts.test.includes("npm run test:alb135"), "ALB-135 is absent from npm test");
    check(roadmap.includes("Product UI finalization — ALB-135 audit complete"), "roadmap UI milestone is missing");
    check(readme.includes("ALB-135 starts product UI finalization"), "README UI milestone is missing");
    check(index.includes("ALB-135_PRODUCT_UI_FINALIZATION.md"), "engineering index omits ALB-135");

    console.info(`PASS ALB-135: ${assertions} product UI finalization assertions`);
} catch (error) {
    console.error(`FAIL ALB-135: ${error.message}`);
    process.exitCode = 1;
}
