const ERRORS = Object.freeze({

    UNKNOWN: "UNKNOWN_ERROR",

    INITIALIZATION_FAILED: "INITIALIZATION_FAILED",

    SHUTDOWN_FAILED: "SHUTDOWN_FAILED",

    INVALID_CONFIGURATION: "INVALID_CONFIGURATION",

    INVALID_TEMPLATE: "INVALID_TEMPLATE",

    INVALID_PHOTO: "INVALID_PHOTO",

    INVALID_DOCUMENT: "INVALID_DOCUMENT",

    DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",

    TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",

    PHOTO_NOT_FOUND: "PHOTO_NOT_FOUND",

    OUTPUT_FOLDER_NOT_FOUND: "OUTPUT_FOLDER_NOT_FOUND",

    EXPORT_FAILED: "EXPORT_FAILED",

    SAVE_FAILED: "SAVE_FAILED",

    OPEN_FAILED: "OPEN_FAILED",

    CLOSE_FAILED: "CLOSE_FAILED",

    GENERATION_FAILED: "GENERATION_FAILED",

    PIPELINE_FAILED: "PIPELINE_FAILED",

    JOB_FAILED: "JOB_FAILED",

    QUEUE_FAILED: "QUEUE_FAILED",

    MEMORY_LIMIT_EXCEEDED: "MEMORY_LIMIT_EXCEEDED",

    CACHE_ERROR: "CACHE_ERROR",

    VALIDATION_FAILED: "VALIDATION_FAILED",

    RECOVERY_FAILED: "RECOVERY_FAILED",

    CANCELLED: "OPERATION_CANCELLED"

});

export default ERRORS;