export const GenerationStates = Object.freeze({

    IDLE: "IDLE",

    VALIDATING: "VALIDATING",

    LOADING_TEMPLATE: "LOADING_TEMPLATE",

    SCANNING_PHOTOS: "SCANNING_PHOTOS",

    OPENING_DOCUMENT: "OPENING_DOCUMENT",

    SCANNING_LAYERS: "SCANNING_LAYERS",

    RESOLVING_SMART_OBJECTS: "RESOLVING_SMART_OBJECTS",

    MATCHING_PHOTOS: "MATCHING_PHOTOS",

    REPLACING_PHOTOS: "REPLACING_PHOTOS",

    SAVING: "SAVING",

    EXPORTING: "EXPORTING",

    CLEANUP: "CLEANUP",

    COMPLETED: "COMPLETED",

    ERROR: "ERROR",

    CANCELLED: "CANCELLED"

});